In [8]:
import torch

### Initialization

In [9]:
x = torch.empty(5,3)
x

tensor([[-4.6559e+00,  4.5556e-41, -2.9088e+11],
        [ 3.0847e-41,  1.4013e-45,  0.0000e+00],
        [ 2.9265e+11,  3.0847e-41,  3.9236e-44],
        [ 3.0847e-41,  6.5646e+00,  4.5556e-41],
        [ 2.8026e-45,  4.5556e-41,  2.8026e-45]])

In [10]:
x = torch.rand(5,3)
x

tensor([[0.1603, 0.1252, 0.5681],
        [0.8614, 0.2287, 0.3855],
        [0.3432, 0.2954, 0.9027],
        [0.0100, 0.9979, 0.5678],
        [0.2202, 0.5591, 0.9453]])

In [11]:
x = torch.zeros(5,3, dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [12]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [14]:
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
x = torch.rand_like(x)
x

tensor([[0.3360, 0.9301, 0.8464],
        [0.5471, 0.7515, 0.7877],
        [0.6699, 0.2921, 0.3301],
        [0.3144, 0.7201, 0.2268],
        [0.8235, 0.9773, 0.8469]])

### Operations

In [16]:
x = torch.rand(5,3)
y = torch.rand(5,3)
torch.add(x,y)

tensor([[0.9520, 0.0877, 0.6010],
        [1.3538, 1.2666, 1.9195],
        [0.4750, 0.8745, 1.5968],
        [1.0922, 0.7128, 1.2760],
        [0.9915, 0.6300, 0.7664]])

In [18]:
result = torch.empty(5,3)
torch.add(x,y, out = result)
result

tensor([[0.9520, 0.0877, 0.6010],
        [1.3538, 1.2666, 1.9195],
        [0.4750, 0.8745, 1.5968],
        [1.0922, 0.7128, 1.2760],
        [0.9915, 0.6300, 0.7664]])

### Matrix-op

In [19]:
x[:,1]

tensor([0.0699, 0.5648, 0.5361, 0.2414, 0.2291])

In [20]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.6204])
0.6204344034194946


### Numpy-Bridge

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [30]:
x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

In [31]:
y = x.numpy()
y

array([1., 1., 1., 1., 1.], dtype=float32)

In [32]:
x += 1
x

tensor([2., 2., 2., 2., 2.])

In [33]:
y

array([2., 2., 2., 2., 2.], dtype=float32)

In [35]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA

In [38]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    # directly create a tensor on GPU
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    print(z)
    print(z.to("cpu", torch.double))

tensor([[0.0987, 0.6612, 0.1608, 0.7606, 0.3046, 0.6413, 0.7238, 0.3093],
        [0.7146, 0.7766, 0.9764, 0.2305, 0.0077, 0.1184, 0.9636, 0.6213]])
tensor([[0.0987, 0.6612, 0.1608, 0.7606, 0.3046, 0.6413, 0.7238, 0.3093],
        [0.7146, 0.7766, 0.9764, 0.2305, 0.0077, 0.1184, 0.9636, 0.6213]],
       dtype=torch.float64)
