In [1]:
import torch

In [2]:
x = torch.ones(2,2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
z = y * y * 3
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

### Gradients

In [5]:
out.backward()

In [6]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [7]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
# Use detach to get a new Tensor with the same content but does not require gradients
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
y

True
False


tensor([[1., 1.],
        [1., 1.]])